---
title: "EJ_Data_Exploration"
author: "Mario"
date: "7/2/2019"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

#library load

library(tidyverse)
library(sf)
library(leaflet)
library(tmap)
library(raster)
library(maptools)
library(rgdal)



```


```{r}

#read in CalEnvironScreen June 2018 shapefile

ces_shapefile <- st_read(dsn = "CalEnvironScreen/CESJune2018Update_SHP", layer = "CES3June2018Update")


#read column names for shapefile
class(ces_shapefile)


```

###CIScore Percent

```{r}

#set tmap as interactive mode
tmap_mode("view")

#read in visual for CalEnvironScreen with polygons set the CalEnvironScreen Score (Pollution Burden * Population Characteristics) AS PERCENTILE
tm_shape(ces_shapefile) +
  tm_polygons("CIscoreP") 

```

###Poverty Percent

```{r}


tmap_mode("view")
#read in visual for CalEnvironScreen with polygons set the POVERTY level AS PERCENTILE
tm_shape(ces_shapefile) +
  tm_polygons("povP")

```


```{r}

#read in fracking data as csv data.frame
ASTABLE_well_location <- read.csv("Well_Data/AllWells_table/AllWells_20190724.csv")

#convert table to spatial data
ASSPATIAL_well_location <- st_as_sf(ASTABLE_well_location, coords = c("Longitude", "Latitude"), crs = 4326)

#filter out only Oil and Gas Wells (OG) and ACTIVE wells
ACTIVE_well_location <- ASSPATIAL_well_location %>%
  filter(WellType == "OG" & WellStatus == "Active") 

#filter out only Oil and Gas Wells (OG) and NEW wells (Recently permitted well; in the process of being drilled)
NEW_well_location <- ASSPATIAL_well_location %>% 
  filter(WellType == "OG" & WellStatus == "New") 
             

```



```{r}

#display ACTIVE well location as clusters across CA
leaflet(data = ACTIVE_well_location) %>% 
  addTiles() %>% 
  addMarkers(clusterOptions = markerClusterOptions())

```


```{r}

#display NEW well location as clusters across CA
leaflet(data = NEW_well_location) %>% 
  addTiles() %>% 
  addMarkers(clusterOptions = markerClusterOptions())



```


##Find number of NEW well locations in specific tracts

```{r}


#st_transform CRS for both to match
ces = st_transform(ces_shapefile, 4326)

new_well = st_transform(NEW_well_location, 4326)

#use st_intersect to get instersection of points (new_well) in polygons (ces).

NEW_intersect <- st_intersection(ces, new_well)


#subset count of well locations in polygons

new_well_count <- NEW_intersect %>% 
  group_by(tract) %>% 
  count()

new_well_count <- as.data.frame(new_well_count)[,-3]


```


##Find number of ACTIVE well locations in specific tracts

```{r}


#st_transform CRS for ACTIVE wells match

active_well = st_transform(ACTIVE_well_location, 4326)



#use st_intersect to get instersection of points (new_well) in polygons (ces).

### Allison notes: this is confusing to me... aren't both ces here (just has a latitude & longitude coordinate for each row, so aren't these just spatial points) and new_well locations both spatial points? Then trying to find an intersection doesn't make sense. Intersection works when trying to find points within a polygon.

ACTIVE_intersect <- st_intersection(ces, active_well)


#subset count of well locations in polygons

# So if there are no intersections because they're both spatial points, then NEW_intersection might only contain the one place where both a well location and the ces location point are exactly the same (but either way, it doesn't really make sense to try to find intersections between two sets of spatial points)...

# Which means that this won't work how you want it to. 

active_well_count <- ACTIVE_intersect %>% 
  group_by(tract) %>% 
  count()

active_well_count <- as.data.frame(active_well_count)[,-3]

```


##Merge well count back into CES shapefile


```{r}

#outer merge CalEnvironscree with new_well_count, NA for those tracts with no value (rename column new_wells)
ces_nwell_only <- merge(ces, new_well_count, by = "tract", all = TRUE) %>% 
  rename(new_wells = n)


#outer merge CalEnvironscree with active_well_count, NA for those tracts with no value (rename column new_wells)

ces_well_FINAL <- merge(ces_nwell_only, active_well_count, by = "tract", all = TRUE) %>% 
  rename(active_wells = n)

```


#View CIS Scores and New Wells

```{r}


tmap_mode("view")

#read in visual for CalEnvironScreen with polygons set the CalEnvironScreen Score, New Wells and Poverty Percentile by Census Tract (add OpenStreetMap)
tm_shape(ces_well_FINAL) +
  tm_polygons(c("CIscoreP", "povP", "new_wells", "active_wells")) +
  tm_facets(sync = TRUE, ncol = 2) +
  tmap_options(limits = c(facets.view = 4)) +
  tm_basemap(c("OpenStreetMap"))

```


